### ISSUE TITLE
Upgrade gocql version causes 10x incoming network data size

### ISSUE THREAD

**Issue by YeminLi** [gocql/gocql#1414]
### What version of Cassandra are you using?
 Scylla 3.0.8

### What version of Gocql are you using?
Gocql `v0.0.0-20200131111108-92af2e088537`

### What did you do?
Upgraded Gocql from `v0.0.0-20190423091413-b99afaf3b163` to `v0.0.0-20200131111108-92af2e088537`, and restarted the application.

### What did you expect to see?
The `Interface Rx Bps` in the scylla dashboard should be consistent with the value before upgrade.
The `Network In (Bytes)` in AWS EC2 dashboard should be consistent with the value before upgrade.

### What did you see instead?
About 9 to 10 times increasing for `Interface Rx Bps` and `Network In (Bytes)` value, which causing performance issue to the cluster. Downgrading gocql resolved the issue.

The application only queries the database and does not write any data.

**Comment by martin-sucha** [comment]
Hi @YeminLi ,

thanks for the report!

Could you please try with the latest `master`? There were a few fixes for regressions in token aware host policy since 92af2e088537 (#1400 , #1405), especially the former could cause requests to be directed to random nodes, which need to redirect the request in turn, if you use ShuffleReplicas.

If the latest master does not fix your issues, could you please try to narrow down the issue to a commit with `git bisect`? There are quite a few (38) commits in the range b99afaf3b163..92af2e088537.

**Comment by martin-sucha** [comment]
Hi @YeminLi did the above help you resolve the issue? Can we close this?

**Comment by YeminLi** [comment]
> Hi @YeminLi did the above help you resolve the issue? Can we close this?

Ya. I think this issue has been fixed.
