### ISSUE TITLE
CPU hogging / unresponsive application 

### ISSUE THREAD

**Issue by DigitalMarc** [gocql/gocql#1481]
### What version of Cassandra are you using?
3.11

### What version of Gocql are you using?
github.com/gocql/gocql v0.0.0-20200814012250-f09c24d7b32a

### What did you do?
execute a bunch of read queries in parallel

### What did you expect to see?
application keeps running forever

### What did you see instead?
The application runs fine using around 20-25% of the CPU with a very low memory footprint.
Sporadically, after running for a bit of time (in the couple of minutes range) the application starts behing unresponsive even to pprof endpoint queries and uses 90-100% of the CPU (1 core it seems) (very low memory footprint still).

### Describe your Cassandra cluster
The sample code to reproduce the issue has been made with a single cassandra 3.11 node.
Similiar behavior has been seen on various cassandra and scylla multi nodes clusters.

The following code as been used to ease the reproduction of the issue:
``` go
func main() {
	runtime.SetMutexProfileFraction(1)
	runtime.SetBlockProfileRate(int(time.Second.Nanoseconds() * 1))
	go func() {
		http.ListenAndServe(":7778", nil)
	}()

	cluster := gocql.NewCluster("192.168.0.10")
	cluster.ProtoVersion = 4
	cluster.Authenticator = gocql.PasswordAuthenticator{
		Username: "cassandra",
		Password: "cassandra",
	}

	session, err := cluster.CreateSession()
	if err != nil {
		panic(err)
	}

	for {
		for i := 0; i < 2000; i++ {
			go func() {
				query := "SELECT time, value FROM ks.table where id = 261713490 LIMIT 720"
				cqlQuery := session.Query(query)
				iter := cqlQuery.Iter()
				if err := iter.Close(); err != nil {
					fmt.Printf("err : %v \n", err)
				}
			}()
		}
		time.Sleep(500 * time.Millisecond)
	}
}
```

Here is the output with gocql_debug tag:
```
go run -tags "gocql_debug" main.go
2020/08/14 16:29:33 gocql: Session.handleNodeUp: 192.168.0.10:9042
2020/08/14 16:30:33 Session.ring:[192.168.0.10:UP]
```

I've attached whatever I can get from pprof (block; mutex; goroutine and cpu profile) before the application hangs:
[cpu.zip](https://github.com/gocql/gocql/files/5075163/cpu.zip)
[cpu.pdf](https://github.com/gocql/gocql/files/5075165/cpu.pdf)
[block.txt](https://github.com/gocql/gocql/files/5075166/block.txt)
[goroutines.txt](https://github.com/gocql/gocql/files/5075168/goroutines.txt)
[mutex.txt](https://github.com/gocql/gocql/files/5075170/mutex.txt)

**Comment by DigitalMarc** [comment]
Any idea/recommendation of a place we can look at to investigate? @martin-sucha @Zariel @jeffwidman

**Comment by martin-sucha** [comment]
Hi @DigitalMarc, I see there is `writeCoalescer` in the cpu profile. Please try whether the patch in https://github.com/gocql/gocql/pull/1393 helps.

**Comment by Zariel** [comment]
When it hangs kill it with SIGABRT and post the stack trace, nothing provided looks out of the ordinary

**Comment by DigitalMarc** [comment]
Thanks for your feedback. Please find attached the stacktrace:

[logfile.zip](https://github.com/gocql/gocql/files/5156502/logfile.zip)

**Comment by cdent** [comment]
I have what might be a same or similar issue. go-based web service that uses gocql running in a container. When the service is otherwise idle, CPU usage will dramatically rise, HTTP requests to /health endpoint will get no response. I've instrumented the container so that when the orchestrator decides to kill it a strack trace is dumped. That's attached. From what I can tell nothing is happening other the http listener listening, a signal listener listening, and several gocql created goroutines, including some from `conn.go`. I haven't tried #1393 but will see if I can give that a try this week.

[trace.txt](https://github.com/gocql/gocql/files/5224741/trace.txt)

The trace is gocql from commit 420e3b873d91 .

**Comment by DigitalMarc** [comment]
@martin-sucha @cdent I've tried #1393 but the problem remains.

**Comment by cdent** [comment]
I have #1393 running now in the place where I'm seeing the stalls. Will report back if any change in behavior.

In the meantime, is anyone able to make any theories from the traces that @DigitalMarc and I have suppled?

**Comment by cdent** [comment]
#1393 doesn't seem to be making any difference for me. I've attached another trace log from a recent failure (with the patch in place):

[apilog.txt](https://github.com/gocql/gocql/files/5257046/apilog.txt)

**Comment by MarcMagnin** [comment]
I've got some good news.
I've updated to the latest golang (from 1.14.1 to 1.15.5 as the time of writing) and it looks like the issue is gone.
From my investigation the problem looks to come from blocking reads or writes onto the net.Conn.
Since I've updated golang everything seems to work ok so far (no freezing issue yet).
I suspect that the fix may come from this part of the release notes:
```
https://golang.org/doc/go1.15#net
If an I/O operation exceeds a deadline set by the Conn.SetDeadline, Conn.SetReadDeadline, or Conn.SetWriteDeadline methods, 
it will now return an error that is or wraps os.ErrDeadlineExceeded. 
This may be used to reliably detect whether an error is due to an exceeded deadline.
Earlier releases recommended calling the Timeout method on the error, but I/O operations can return errors for which 
Timeout returns true although a deadline has not been exceeded.
```

Let me know how this goes on your side.

**Comment by cdent** [comment]
> I've got some good news.

Woo! I'll give this a try as soon as I'm able and report back.

**Comment by cdent** [comment]
> Let me know how this goes on your side.

I'm into about 3 days without seeing the problem, when I used to see it multiple times per day. Took me longer to test it than I wanted because upgrading to a new go needed an upgrade to new bazel go_rules and that changed the paths of produced binaries and broke a bunch of stuff and...

Yeah...

But now that that's cleared up, we're on go 1.15 and it's looking better. Will come back again if/when it is more or less sure.

**Comment by DigitalMarc** [comment]
We had no issues so far also. I'm closing it but feel free to reopen if any related issue arise.

**Comment by Ashtonian** [comment]
Anyone have a upstream issue to reference ?
