### ISSUE TITLE
Unable to get error message from sessions.Iter struct after failed cassandra query

### ISSUE THREAD

**Issue by tkmishra** [gocql/gocql#1566]
Please answer these questions before submitting your issue. Thanks!

### What version of Cassandra are you using?
3.11.9

### What version of Gocql are you using?
master branch

### What version of Go are you using?
1.15

### What did you do?
Trying to perform retry in case of cassandra query failures. But unable to get error as there was no way to get error using Iter struct in sessions.go

### What did you expect to see?
I am expecting a way to receive error messages from Iter struct similar in a same way we have option to get host() or NumRows()

### What did you see instead?
Looking on the sessions.go file, we need an method to return error something  like GetError() or any other way to fetch error messages would also server the purpose
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
 peer | rpc_address
------+-------------

- rebuild your application with the `gocql_debug` tag and post the output

**Comment by martin-sucha** [comment]
Hello!

You can get the error from [Iter.Close](https://pkg.go.dev/github.com/gocql/gocql#Iter.Close) like this:

```go
iter := ...
for iter.Scan(&column1, &column2) {
	// process row
}
err := iter.Close() // err contains first error from either iter.Scan() or iter.Close()
```

Since the iter.Scan argument list can grow long, there is also `Scanner`, which is demonstrated in the [main package example ](https://pkg.go.dev/github.com/gocql/gocql#example-package).

If you want retries, the driver has them built-in. You need to configure the retry policy and mark queries that can be retried as idempotent. See [Retries and speculative execution](https://pkg.go.dev/github.com/gocql/gocql#hdr-Retries_and_speculative_execution) in the documentation. If you think there is something missing in the docs, please let me know and we can add it to the documentation.

**Comment by tkmishra** [comment]
I guess I was trying to re-invent the wheel when it was already there !!! Now I can reuse the existing gocql.RetryPolicy instead of implementing backoff.RetryNotify at my application level.

Thanks  @martin-sucha  for pointing me to gocql.RetryPolicy interface. This will solve my issue. Appreciate your immediate help.
