### ISSUE TITLE
Support for UDTs (2.1)

### ISSUE THREAD

**Issue by al3xdm** [gocql/gocql#175]
So one of the upcoming features of 2.1 is UDTs (User Defined Types https://issues.apache.org/jira/browse/CASSANDRA-5590).

Given the CQL:

```
CREATE TYPE name (
    first_name text,
    last_name text
);
  
CREATE TABLE user (
    id uuid PRIMARY KEY,
    user_name name
    email text
);
```

And a Go struct:

```
type Name struct {
    First string,
    Last string
}

type User struct {
    Id gocql.UUID
    Name Name
    Email string
}
```

We need to be able to do this:

```
var user User

err := session.Query(`SELECT id, name, email FROM users WHERE id = ? LIMIT 1`, id).Scan(&user.Id, &user.Name, &user.Email)
```

Otherwise the Driver won't be CQL compliant. There is the option to do dot notation for nested fields, like:

```
var user User

err := session.Query(`SELECT id, name.first, name.last, email FROM users WHERE id = ? LIMIT 1`, id).Scan(&user.Id, &user.Name.First, &user.Name.Last, &user.Email)
```

However drivers have to implement the first option too.

Previously the general consensus has been against struct marshalling, any idea how you'd like this handled? I'm happy to build this once I know what will get merged.

**Comment by nemothekid** [comment]
Coming back to this - is there any reasons why gocql shouldn't support tagged types (like most common Marshal libraries like JSON).

For example, the first example could be done this way:

```go
type Name struct {
    First string `cql:"first_name"`
    Last string `cql:"last_name"`
}
```

and, the driver could use `reflect` much like the JSON library to find the appropriate tags/fields.

```
err := session.Query(`SELECT id, name, email FROM users WHERE id = ? LIMIT 1`, id).Scan(&user.Id, &user.Name, &user.Email)
```

What I would *also* like to see is the ability to do something like `MapScan` for structs, so if I table like:

```
CREATE TABLE user (
    id uuid PRIMARY KEY,
    user_name name
    email text
);
```

I want to be able to:

```
var u User
iter := session.Query("SELECT * FROM users").Iter()
for iter.StructScan(&u) {
    // do anything
}
```

with this - I don't even see the need to have a CQLMarshaller/Unmarshaller type.

**Comment by 0x6e6562** [comment]
The reason why cqlr was written in the first place was threefold: 

* It is/was inevitable that people want a convenient way to bind application level struts, especially given the introduction of of UDTs into the database.
* UDTs were/are in a state of evolution in the protocol (see for example the frozen keyword).
* There is quite a bit of work and discussing to be done to land a complete binding feature set, which is unlikely to occur in one patch, so it seemed to make sense to build an explicit POC for this feature.

So whilst I think that ultimately struct binding should be supported by gocql, I think the easiest way to mature out the approach is via a layered POC that can get integrated into the core when it has been tested, supports all the necessary features and that we're happy with the maintenance implications. It just seems to me to be an easier way to get things done without having to gain consensus on a difficult design upfront. The working code can then serve as an uber-pull-request back into the core.

**Comment by 0x6e6562** [comment]
Regarding the behavior for missing or erroneous binding meta data: I don't think the library should panic. If we want to allow dynamic binding, then mismatches are inevitable and we should have a more explicit way to pass the error back to the application. Panicking should only be used for unavoidable scenarios. Binding mismatches are not unavoidable, they will occur naturally as two statically typed systems (i.e. Cassandra and Golang) get out of sync.

**Comment by 0x6e6562** [comment]
So anyway, patches are welcome, both in gocql and cqlr , so you're free to choose the way you'd like to see first class struct binding introduced.

**Comment by nemothekid** [comment]
I don't think struct tagging is terribly complicated - the work is already done by the standard library and is idiomatic go. In any case I understand why in the past it was better to have this functionality outside of the core library but it seems the trend for Cassandra is to have more full featured clients to take advantage of Cassandra's features. While I understand gocql has leaned toward a leaner client, I'd rather see support for simple struct tagging rather than trying to plan to have feature parity with something like SQLAlchemy. At the same time, we have thought about adding some of DataStax java driver features to gocql such as datacenter & token awareness but we haven't been able to decide how to move forward with this.

--

IIRC, with the `Scan` function if you pass a mismatched type, you get a panic right? I might be mistaken because we tend to raise most errors to panic. In any case I think the best solution would be to do whatever the library does now. We will start on a fork.

**Comment by 0x6e6562** [comment]
>I don't think struct tagging is terribly complicated - the work is already done by the standard library and is idiomatic go.

Sure, you've got a point. I'm not saying that the mechanics of struct tagging are rocket science (after all, struct tagging is supported in cqlr). I was just thinking about all of the nesting you would need to support, the fact that UDTs are due to evolve by the Cassandra hits 3.0 or 3.1 and just generally coming up with a set of test cases that we'd want to support. I was merely referring to the amount of work required to introduce the change but still keep the library in a stable state.

>In any case I understand why in the past it was better to have this functionality outside of the core library but it seems the trend for Cassandra is to have more full featured clients to take advantage of Cassandra's features.

You may well be right about current trends in Cassandra clients. The approach taken thus far with gocql is one of pragmatism: we're a tiny open source project with no engineering budget other than that what is donated by maintainers and contributors. We want to keep the library stable and robust, but also want to move it forwards. So when we talk about layering as a way to introduce new features, this is only so that we can take small steps towards a bigger goal without introducing too many bugs and other maintenance hazards in one big step. If we were DataStax, we'd probably have staff to work on the library full-time and a product driver and we'd probably make bigger changes quicker.

>  While I understand gocql has leaned toward a leaner client, I'd rather see support for simple struct tagging rather than trying to plan to have feature parity with something like SQLAlchemy.

Yes, it would be even more difficult to find consensus about putting something akin to SQLAlchemy into the core.

> At the same time, we have thought about adding some of DataStax java driver features to gocql such as datacenter & token awareness but we haven't been able to decide how to move forward with this.

Are you referring to stalled discussions such as #200?

> IIRC, with the Scan function if you pass a mismatched type, you get a panic right?

I'm not 100% sure that you are referring to a known bug, as I'm unaware of this behavior. I would hope that we use the `unmarshalErrorf()` function, but it might be possible that there are instances where this is not the case. If that is so, I think it would be good to raise this as a bug.

> I might be mistaken because we tend to raise most errors to panic.

Are you referring to a gocql style of raising errors to panic, or a style that is internal to your organization?

> We will start on a fork.

Very cool. Don't be too put off by what I'm saying about the approach - ultimately I'm coming from a very maintenance-orientated perspective.

**Comment by nemothekid** [comment]
>Are you referring to a gocql style of raising errors to panic, or a style that is internal to your organization?

It turns out it was our code style, gocql does not panic. However, after looking over #308, I decided to hold off on this until #308 lands (I'm not sure if it would conflict or not, but I want to avoid doing these 2 PRs simultaneously).

**Comment by 0x6e6562** [comment]
>It turns out it was our code style, gocql does not panic.

OK, good to know.

>However, after looking over #308, I decided to hold off on this until #308 lands (I'm not sure if it would conflict or not, but I want to avoid doing these 2 PRs simultaneously).

Yes, I was thinking that #308 might be relevant for some of your requirements. But #308 is big, and I am hoping that we extract a series of patches to give us a more maintainable migration. You may want to participate in the shaping of #308, depending on what your needs are.

**Comment by 0x6e6562** [comment]
The fact that #352 has now landed might be of interest to those following this issue.

**Comment by Zariel** [comment]
If anyone has any comments on the API to implement this in #369 I would be happy to hear it.
