### ISSUE TITLE
How to use batches and goroutines?

### ISSUE THREAD

**Issue by purohit** [gocql/gocql#301]
Hello,

I'm confused about how to use connections, batches, etc with multiple goroutines. Basically, I'm reading from a large CSV file and am preparing batch inserts. After reading N rows per batch, I send the batch through a channel, to be executed by a goroutine using the shared session. However, I get this error every time I try to `session.ExecuteBatch`: `write tcp 123.456.789.1:9042: use of closed network connection`.

So, I have the wrong architecture but I'm not sure why. Here's how I have it now:

1. Spawn 8 goroutines, that wait on an incoming channel C of *gocql.Batch.
2. Read the CSV file. For every N rows, create a new session.NewBatch, add the rows to the batch using `batch.Query`, and pass the batch C.
3. Go-routine sees the batch in C, attempts to execute it use the shared session: `session.ExecuteBatch(<- C)`.
4. Get the error described above.

How am I doing this incorrectly? A few follow-up questions:

1. Do I use the same session for all the batches?
2. Do I need to change something in the connection pool?

Thank you.

**Comment by phillipCouto** [comment]
Could to please post some code it will help us understand the problem.

**Comment by purohit** [comment]
Gladly. I've removed a lot of error handling and other code, but this is the meat:

```go
func main() {
	cluster := gocql.NewCluster("node1")
	cluster.Keyspace = "mydata"
	session, err := cluster.CreateSession()
	defer session.Close()
	file, err := os.Open(filename)
	defer file.Close()
	csvFile := csv.NewReader(file)
	header := getHeader(csvFile)
	q := buildQueryString(header)
	in := make(chan *gocql.Batch, 0)
	var wg sync.WaitGroup
	for i := 0; i < goroutines; i++ {
		go processBatches(session, in, &wg)
	}
	counter := 0
	curBatch := session.NewBatch(gocql.LoggedBatch)
	for {
		row, err := csvFile.Read()
		curBatch.Query(xxx) // Add a line here to the batch from row
		counter++
		if counter == gocql.BatchSizeMaximum {
			in <- curBatch
			curBatch = gocql.NewBatch(gocql.LoggedBatch)
			counter = 0
		}
	}
	close(in)
	wg.Wait()
}

func processBatches(s *gocql.Session, in chan *gocql.Batch, wg *sync.WaitGroup) {
	wg.Add(1)
	for batch := range in {
		for {
			if err := s.ExecuteBatch(batch); err != nil {
				log.Printf("Couldn't execute batch: %s", err) // Always get an error here.
				continue
			}
			break
		}
	}
	wg.Done()
}
```

**Comment by phillipCouto** [comment]
Can you check the err at the session,err := cluster.CreateSession()

You should be checking all the err variables you have defined to make sure the error isn't actually caused by something else. Your hostname or even the session configuration for gocql could be wrong but your not checking an error until you are executing a batch.

**Comment by purohit** [comment]
@phillipCouto: there are no errors except the one at `s.ExecuteBatch`, which is why I took them out for this example (""I've removed a lot of error handling and other code"). In my actual code, I check them!

@0x6e6562: I've updated my code above to be a full program -- I get the same errors.

**Comment by phillipCouto** [comment]
Can you change the line:
```
if counter == gocql.BatchSizeMaximum {
```
To:
```
if counter == 1000 {
```

**Comment by purohit** [comment]
@phillipCouto : that works, thank you! Even with 8 goroutines. Now you'll have to tell me why :D

**Comment by phillipCouto** [comment]
Batches in cassandra are meant to be small. Cassandra at least in the newer versions throws a warning in the log when a batch is executed that is larger than a predefined size. The default size to trigger the warning is 5kb. The reason for this is batches in Cassandra are not like batch operations in other databases. A batch should only consist of DML queries that will affect only 1 partition. Also since batches has a weak form of atomicity they must be small to guarantee their execution on replicas. 

With this knowledge gocql.BatchSizeMaximum is used to make sure we do not allow more queries in a batch than the frame format supports. The cluster practically speaking may fail to handle batch sizes significantly smaller as the the speed of the nodes + networking and size of each query being executed varies between implementation.

I highly suggest you read further the details of batch operations in Cassandra so you can model your application that will behave more appropriately with Cassandra.

In regards to your application will you be bulk inserting CSV files into Cassandra?

**Comment by purohit** [comment]
Thanks, Phillip. That is a detailed and useful explanation. I believe I fell into the trap of

> Batches are often mistakenly used in an attempt to optimize performance.
http://www.datastax.com/documentation/cql/3.1/cql/cql_using/useBatch.html

Indeed, I am attempting to bulk insert CSV files into Cassandra. 

From https://medium.com/@foundev/cassandra-batch-loading-without-the-batch-keyword-40f00e35e23e it seems like the best approach would be not to use batches, and to use some sort of async statement execution. What I had before was just using 8 goroutines to execute query by query, but I thought performance was pretty bad so I wasn't sure what else I could try.

**Comment by phillipCouto** [comment]
Well my recommendation is create a goroutine for each CSV file to be inserted. Let that goroutine execute the queries directly. This will allow gocql to distribute the queries among the nodes in your cluster and improve application throughput.

To further improve the import process you have to design the table in a way that will benefit from batches based on the data you are importing.

For example if each CSV file represents data from a single day in a year your Primary key could be a composite key where the partition key is the date and the time is the second component of your primary key:
```
CREATE TABLE records (date text, time text, value int, PRIMARY KEY(date,time));
```

You can then create batches of 1000 for that CSV file that will likely execute faster than the execute each record individually approach.

Cassandra is fairly complex in nature and requires a fair understanding of the internals to create efficient applications in reading and writing to Cassandra.

**Comment by purohit** [comment]
Phillip,

Thanks for the advice. I will do that -- goroutine per CSV file. I may skip the batches entirely because I have wide rows: a single row is around 8kb.

**Comment by phillipCouto** [comment]
No problem glad we could help!
