### ISSUE TITLE
Slight loss of precision converting Time->UUID->Time

### ISSUE THREAD

**Issue by kemist** [gocql/gocql#344]
If I take a time struct, convert it to a UUID and then back into a time struct I find that it's missing 2 decimal places of precision (nsecs).

Repro code:
https://gist.github.com/kemist/4b1d5a50b1f1f31fb659

For example
```go
Original := time.Now.Utc()
Converted := UUIDFromTime(Original).Time()
```
Will output something like:
```
original:  2015-04-07T03:34:36.874143331
converted: 2015-04-07T03:34:36.8741433
```

**Comment by nemothekid** [comment]
(Time)UUIDs are only accurate to 100 nanosecond intervals. This is by design - http://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_.28MAC_address_.26_date-time.29

**Comment by tux21b** [comment]
That's intentional. Go uses 96 bits (and a separate location info) for a time, UUIDv1s on the other hand, are just using 60 bits. Also note, that production code should never convert UUIDs to times and vice versa. Think of an UUID as an unique identifier that can be (roughly) sorted by time. If you need the time in your application, store it separately.

Many UUID libraries do not even provide functions to convert them from / to times, but in my opinion such functions are quite handy when you need to convert a traditional database for example.

**Comment by 0x6e6562** [comment]
As @nemothekid and @tux21b have indicated, the purpose of the timeuuid type is to provide a monotonically increasing unique identifier and as such should not be used for applications that require high-fidelity timestamp logic.

If you are happy with this explanation @kemist, would you like to keep this issue open or is it closable?

**Comment by kemist** [comment]
@nemothekid @tux21b @0x6e6562 Thanks for the explanations! Makes perfect sense
