### ISSUE TITLE
When a host is down it blocks the PolicyAwareConnectionPool readers until timeout

### ISSUE THREAD

**Issue by Zariel** [gocql/gocql#376]
As discovered by @nemothekid when a host is down (down in gossip) it will still exist in the `system.peers` table, this means that we will try to add it to the pools continually if discovery is enabled.

The cause of this is that when `SetHosts` is called it acquires the write lock, then tries to creating a host pool which dials the down node. Which in turn blocks until timeout before returning.

**Comment by Zariel** [comment]
@nemothekid I have a commit to fix this but I want to write some tests to verify that it works correctly and fixes this issue.

The test suite fails on my machine due to 108f44b198d3cb9d069876575a5a3fe7454d674a which I think I will need to submit as a separate PR.

**Comment by Zariel** [comment]
I havnt been able to replicate that this, my theory was that if a host is down and just hangs indefinitely then the pool will block to dial it. But this doesnt seem to be the case.

Though I have noticed that we dont set the timeout when dialing a TLS conn.

**Comment by Zariel** [comment]
Im not entirely sure this is actually an issue after spending the day trying to replicate this.

**Comment by nemothekid** [comment]
I think the proper solution here would to be implement proper server side events and only query system.peers once - much like the datastax drivers do. 

OTOH, I think your understanding of the issue is wrong - `SetHosts` is only called every 30 seconds, and I see the problem every 10 seconds - the issue potentially happens every query.

Specifically the issue occurs on [connectionpool.go#819](https://github.com/gocql/gocql/blob/master/connectionpool.go#L819) 

1.) `Query.Exec` is called.
2.)  [session.go#159](https://github.com/gocql/gocql/blob/master/session.go#L159) attempts to pick a connection from the pool.
3.) [connectionpool.go#594](https://github.com/gocql/gocql/blob/master/connectionpool.go#L594) chooses a host
4.) [policies.go#161](https://github.com/gocql/gocql/blob/master/policies.go#L161) returns a host based on the token. Now because the lists of hosts to choose from include all the hosts (incl. those which are down) this function may return a down host.
6.) [connectionpool.go#604](https://github.com/gocql/gocql/blob/master/connectionpool.go#L604) calls Pick, which call `pool.fill()` @ [connectionpool.go#682](https://github.com/gocql/gocql/blob/master/connectionpool.go#L682) which eventually calls connect @  [connectionpool.go#807](https://github.com/gocql/gocql/blob/master/connectionpool.go#L807).
8.) This Connect fails (after 600ms) , the pool fails to be filled, and the Pool moves on to the next host which would succeed.

All this happens in the call to `Query.Exec` - not `SetHosts`.

**Comment by Zariel** [comment]
A simple way to solve the blocking is to use a copy on write map instead of holding the write lock whilst connecting.

**Comment by Zariel** [comment]
I think I see a better solution at least for now. In the call to fill at connectionpool.go#L682 it should be ran async and then return a nil conn so that the calling policy will chose another host.

**Comment by Zariel** [comment]
Im still unable to reproduce this in a testable manner, even when just doing a SIGSTOP on one node and trying to query it when other hosts are up in the pool. I think #379 should fix this issue by 024cb82e74a53dcdb96e1ddad83e6832399baf99

**Comment by nemothekid** [comment]
I think for this to be testable, you would have to write a custom policy that only selects dead nodes (maybe the issue can be thought of as gocql blocks readers when a down host is selected)

**Comment by Zariel** [comment]
@nemothekid can you replicate this? Now that #381 has landed it might be worth trying that.

**Comment by nemothekid** [comment]
#381 did solve this issue - although I'm worried that you weren't able to reproduce it.

**Comment by 0x6e6562** [comment]
@nemothekid I still the jury is still out on this issue, I'm not sure we fully understand it yet. As @justinretailnext has pointed out in #382, we probably we need to figure out and agree on a mini-roadmap for this aspect of the library.

**Comment by Zariel** [comment]
I have an inclining as to why my test case didnt reproduce this, ill give it another go soon and check it.
