### ISSUE TITLE
Arbitrary Precision Decimal Library Move

### ISSUE THREAD

**Issue by sudorandom** [gocql/gocql#401]
It looks like the author of the arbitrary-precision decimal library (speter.net/go/exp/math/dec/inf) has moved its canonical location to gopkg.in/inf.v0 (via http://speter.net/).

I'm not 100% sure how you want to handle this, but I thought I'd create an issue to make this project aware.

**Comment by 0x6e6562** [comment]
Thanks very much for pointing this out. The maintenance aspect of 3rd party dependencies is of key importance to the gocql team, so this is very helpful.

In the past I have lobbied the author to (at least mirror) the upstream on Github, since at least then we would have a shared fate when it comes to a `go get`.

I think what we should probably do first is to re-stablish contact with the `dec/inf` maintainer to see what the future plans are.

**Comment by sudorandom** [comment]
@0x6e6562 thanks for the quick response.

In this case, pkg.in is pulling from a mirror that the author has on github: https://github.com/go-inf/inf

It looks like this might a viable alternative or a good additional library to support as well: https://github.com/shopspring/decimal
