### ISSUE TITLE
Failed to create session with real ip

### ISSUE THREAD

**Issue by nguyener** [gocql/gocql#406]
Hi all,
I created a web-application which has gocql as a driver to connect between my app and cassandra db.  When creating a db session, I normally pass in '127.0.0.1' or 'localhost' and it works fine.  However, when I try to use my machine ip instead, I got connection problem ("connect: failed to connect to 'x.x.x.x': dial tcp x.x.x.x:9042: connection refused"

Here my code:
cluster := gocql.NewCluster("x.x.x.x")
cluster.Keyspace = "demo"
cluster.ProtoVersion = 3
cluster.Consistency = gocql.Quorum
session,_ := cluster.CreateSession()

**Comment by tux21b** [comment]
Can you connect to your Cassandra database using telnet? E.g. "telnet x.x.x.x 9042"? If you can't then your Cassandra server is probably just listening on the local loopback device [1] or a firewall is blocking your connection.

You can fix the first issue by setting rpc_address to 0.0.0.0 in your configuration (see http://docs.datastax.com/en/cassandra/2.0/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__rpc_address for more information).

**Comment by nguyener** [comment]
Hi
I set the rpc_address to 0.0.0.0 but still couldnot create a session to Cassandra.  The same for telnet, only work with local host, but not the real ip

nguyener@ubuntu-vm2:~$ telnet 10.120.112.76 9042
Trying 10.120.112.76...
telnet: Unable to connect to remote host: Connection refused
nguyener@ubuntu-vm2:~$ telnet localhost 9042
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

**Comment by nguyener** [comment]
A side note: cqlsh connection failed once rpc_address is set to 0.0.0.0:
nguyener@ubuntu-vm2:~$ cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
nguyener@ubuntu-vm2:~$

**Comment by nguyener** [comment]
It seems to me that cassandra service failed to restart when I set rpc_address: 0.0.0.0
nguyener@ubuntu-vm2:/etc/cassandra$ sudo service cassandra status
 * could not access pidfile for Cassandra

**Comment by 0x6e6562** [comment]
@nguyener I don't think this is an issue with `gocql` per se - this appears to be a general issue with configuring the Cassandra server rather than a bug in the `gocql` client. Because of this, I think that it would be better to close this issue because it creates noise in our issues list that really isn't an issue with our library.

But I would invite you to continue the discussion on the Cassandra server mailing list where there are many community members who can help you out.

If you feel that closing this issue is incorrect, feel free to re-open it and discuss the issues you are experiencing with this library.
