### ISSUE TITLE
Panic with MapScan on a table with UDT

### ISSUE THREAD

**Issue by bkeroackdsc** [gocql/gocql#466]
```sql
CREATE TYPE log_entry ( created_timestamp timestamp, message text);

CREATE TABLE requests_by_id (
  id uuid PRIMARY KEY,
  type int,
  log_entries list<frozen <log_entry>>
);
```

Doing a ``MapScan()`` results in a runtime panic:

```go
rawResult := map[string]interface{}{}
err = s.Query(`SELECT * FROM requests_by_id WHERE id = ?;`, uuid).MapScan(rawResult)
```

```
--- FAIL: TestGetRequest (0.04s)
panic: interface conversion: interface is nil, not *reflect.rtype [recovered]
	panic: interface conversion: interface is nil, not *reflect.rtype

goroutine 286 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
reflect.SliceOf(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/type.go:1656 +0x64
github.com/gocql/gocql.goType(0x7f3ab926b3e0, 0xc208029c80, 0x0, 0x0)
	/home/vagrant/go/src/github.com/gocql/gocql/helpers.go:44 +0x6d0
github.com/gocql/gocql.CollectionType.New(0x3, 0x20, 0x0, 0x0, 0x0, 0x0, 0x7f3ab926b778, 0xc20852f680, 0x0, 0x0)
	/home/vagrant/go/src/github.com/gocql/gocql/marshal.go:1472 +0x9c
github.com/gocql/gocql.(*CollectionType).New(0xc208029ac0, 0x0, 0x0)
	<autogenerated>:168 +0xb2
github.com/gocql/gocql.(*Iter).RowData(0xc208072680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/gocql/gocql/helpers.go:127 +0x201
github.com/gocql/gocql.(*Iter).MapScan(0xc208072680, 0xc2085964b0, 0xc208032870)
	/home/vagrant/go/src/github.com/gocql/gocql/helpers.go:167 +0x49
github.com/gocql/gocql.(*Query).MapScan(0xc208d94600, 0xc2085964b0, 0x0, 0x0)
	/home/vagrant/go/src/github.com/gocql/gocql/session.go:618 +0x8d
```

This is with latest master.

My workaround is to do a ``Scan()`` with just the UDT column (into a properly typed and tagged struct), then a second query with all the other columns using ``MapScan()``.

**Comment by nemothekid** [comment]
Looks like when you have a list of UDTs, get a recursive call into goType.

[helpers.go#44](https://github.com/gocql/gocql/blob/476ff788f787e3510d0208706837441b8673c436/helpers.go#L44)
```go
case TypeList, TypeSet:
		return reflect.SliceOf(goType(t.(CollectionType).Elem))
```

From [frame.go#659](https://github.com/gocql/gocql/blob/bac7de282c0efee311daccf0d5a9e65923ca335f/frame.go#L659), `t.(CollectionType).Elem` is an instance of `UDTTypeInfo`.
```go
case TypeUDT:
		udt := UDTTypeInfo{
			NativeType: simple,
		}
		udt.KeySpace = f.readString()
		udt.Name = f.readString()

		n := f.readShort()
		udt.Elements = make([]UDTField, n)
		for i := 0; i < int(n); i++ {
			field := &udt.Elements[i]
			field.Name = f.readString()
			field.Type = f.readTypeInfo()
		}

		return udt
```

We call `goType(TypeInfo)` on `t.(CollectionType).Elem` (back at [helpers.go#44](https://github.com/gocql/gocql/blob/476ff788f787e3510d0208706837441b8673c436/helpers.go#L44)), which is an instance of `UDTType`. `goType(TypeInfo)` doesn't have a case for `UDTType`s, so it returns nil, resulting in the panic.

The issue here is how will gocql know how what type to unmarshal the struct into?

The library could provide some sort of global type map or `Register(UDTTypeName, interface{})`  and use that in `CollectionType.New` or the library could just unmarshal all UDTs into `map[string]interface{}` by default, and then the developer can override that be doing something like

```go
rawResult := map[string]interface{}{
    "log_entries":[]MyLogEntry{}
}
err = s.Query(`SELECT * FROM requests_by_id WHERE id = ?;`, uuid).MapScan(rawResult)
```

to get a cleaner type.

**Comment by Zariel** [comment]
Thanks @nemothekid option 1 looks like something that would be good to have. Im currently looking at doing option 2, the problem is that the call to CollectionType.New() does not recursively call UDTType.New() for each element, im not quite sure how best to solve that. The problem here is that TypeUDT is missing from goType, but all it can do is allocate `map[string]interface{}`.
