### ISSUE TITLE
panic in connectionpool.go

### ISSUE THREAD

**Issue by jamesrwhite** [gocql/gocql#481]
We're seeing the following panic occur in `connectionpool.go` when we've been running some internal load tests.

The slightly modified stack trace (to remove private paths etc) is below:

```
[Service] Panic : runtime error: invalid memory address or nil pointer dereference at [
    /path/to/app/src/github.com/CrowdSurge/secret/http.go:87 
    /usr/local/go/src/runtime/asm_amd64.s:401 
    /usr/local/go/src/runtime/panic.go:387 
    /usr/local/go/src/runtime/panic.go:42 
    /usr/local/go/src/runtime/sigpanic_unix.go:26 
    /path/to/app/src/github.com/CrowdSurge/gocql/connectionpool.go:672 
    /path/to/app/src/github.com/CrowdSurge/gocql/connectionpool.go:605 
    /path/to/app/src/github.com/CrowdSurge/gocql/session.go:213 
    /path/to/app/src/github.com/CrowdSurge/gocql/session.go:646 
    /path/to/app/src/github.com/CrowdSurge/secret/cassandra.go:191]
```

The relevant lines seem to be `connectionpool.go:605` which is

```go
conn = p.hostConnPools[host.Peer].Pick(qry)
```

It's worth noting we have a fork of this project that is mostly up to date but the exact line numbers may be slightly different to what is in `master` here.

We added in some logging just before that line is called to look at what is in `p.hostConnPools` and what the value of `host.Peer` is, from what I can see `host.Peer` is set to an IP that is not in that map. We did a simple `Println` of the two and an example is as follows:

`2015/10/02 19:16:35 PANIC_LOG map[10.0.12.37:0xc8200be2a0 10.0.14.84:0xc8247de7e0 10.0.13.104:0xc820525880] 10.0.14.120`

We have changed our cassandra cluster recently to upgrade the node instances but the app has been restarted several times since then so I don't think that's the cause. It's also worth noting we can't reproduce this issue reliably but it does appear to be related to putting a considerable amount of load on our app/cassandra as we've never seen this in production before.

Please let me know if there's any additional info I can provide to help, we'll continue to look at what the cause for this is on our side.

Thanks!

**Comment by Zariel** [comment]
Thanks for the report, what version of cassandra is this? I remember reading something about the system.peers table being flaky.

**Comment by jamesrwhite** [comment]
We're using `2.0.16`.

One potential fix we have for this is https://github.com/CrowdSurge/gocql/pull/13/files, I'm going to test if that resolves the issue this afternoon.

**Comment by willejs** [comment]
I think i figured out what this is. We identified the ip addresses as the Elastic Load Balancer addresses that sit in front of cassandra. We use this as a simple cassandra discovery mechanism.

The idea being nodes drop in and out of the elb, and the initial connection retrieves the nodes tables from cassandra and then creates a connection pool from that fetched list. It disregards the initial resolved ip as this shouldn't matter, and we can expect that to change. Obviously the client doesent work like this?

This is a pretty normal operating procedure for elasticsearch, rabbitmq, mongo etc etc.
Could this be the case?

**Comment by willejs** [comment]
@Zariel Any ideas about this? 

Instead of using the resolved dns address as a node in the cluster, could you instead get the required details from the ```system.local```; table on the initially connected node, then add that to ```system.peers``` to build the pool of nodes?

**Comment by Zariel** [comment]
I haven't had much time to look into fixing the root cause of this yet.

The use case of having Cassandra behind a load balancer sounds very odd and is not something I have come across before, its quite surprising because Cassandra itself does load balancing and maintains dynamic cluster state. I can't make comments on Gocql's suitability to talking to Cassandra through a load balancer.

**Comment by willejs** [comment]
The use case really is common for a lot of distributed datastores, and most clients gather the topology from the datastores, not the DNS entry. When you have nodes in autoscaling groups its common to attach them to an elb, this is because the nodes are ephemeral, die, and are often are scaled up & down, so an elb is really a method of autodiscovery. This is also done with other load balancing technologies too. 

The alternative is to list all your nodes in config, which is implied in this library. However writing configs out in yaml and reloading your service when a node dies or the topology changes is painful and slow. We have a dynamic config service that reloads in real time, and has an api, but we still dont really want to trigger config changes when the topology changes.

The java library basically ignores whatever endpoint you give it and creates the topology from system.peers and system.local, [here](https://github.com/datastax/java-driver/blob/61a98e83cf35ae3e979d6073aeb40ba78eed11d5/driver-core/src/main/java/com/datastax/driver/core/ControlConnection.java#L539)
Given the Java library is official, can you support this instead?

**Comment by willejs** [comment]
The python drivers does this correctly too i think [here](https://github.com/datastax/python-driver/blob/56732e4e811f4bf22eaaeae5ffcaf8182d28a17e/cassandra/cluster.py#L2173)

**Comment by willejs** [comment]
I think if this was removed, it would fix the issue
https://github.com/gocql/gocql/blob/master/host_source.go#L48-L55
The code grabs the local peer and system peers anyway, so it doesent need to look at the connection ip address and panic?

**Comment by Zariel** [comment]
The local table does not contain the local nodes `rpc_address` and the peers table does not contain the local node, we do the same thing that the Java driver does is to use the connections address which we made the query with. This is to prevent the case that we remove the connection we refreshed the token ring with on every ring refresh.

The Java driver appears to check if the connections address is an already known node, if it is not then it will not add it to the ring.

Ill take a look when I get time, I think this might depend on having server side events #359.

**Comment by Zariel** [comment]
@willejs I think I have a test which replicates this, but solving it will be fun.

So it looks like cassandra fixed this issue in the latest round of releases, https://issues.apache.org/jira/browse/CASSANDRA-9603 so I might add a flag to enable querying that column which should fix this.

**Comment by Zariel** [comment]
@willejs what version of Cassandra are you running?

**Comment by jamesrwhite** [comment]
@Zariel the version I mentioned above ^^^

**Comment by Zariel** [comment]
Then #504 should fix your issue

**Comment by jamesrwhite** [comment]
Nice, I'll test this out next week and confirm it resolves the issue. Thanks!

**Comment by rcadena** [comment]
I just ran into this issue and was able to replicate it even with a70d1ac9aaf9d1b373cbf3133893b9ff44f8cb33.  I've made a [gist with a test case](https://gist.github.com/rcadena/8b6f83a5e84f4d91dd07).  If you don't have a cassandra instance handy, you can use the provided docker-compose.yml and use Docker Compose and Docker to create a quick instance.

start:

    docker-compose up

In the main.go program, change the node ip/port to your cassandra (or docker host) ip.  The run:

    go run main.go

When it says `"waiting.  go kill cassandra."`, go do so: **panic.**

I noticed, though, that the panic occurs in a different line than in the original description of the issue: **[connectionpool.go:188](https://github.com/gocql/gocql/blob/master/connectionpool.go#L188)**

**Comment by rcadena** [comment]
Thanks to a separate project I have that has vendored deps, I noticed that I could not trigger a panic when I shut down the c* cluster.  gocql is vendored at commit 6e86253e1c7c91bcdcfe3afd6417d3ddfbe5771c  Unfortunately, I don't currently have time to figure try later commits to see where the panics begin.  Maybe that helps narrow this down.

**Comment by rcadena** [comment]
I've worked on this a bit more.  Looks like the algorithm in [roundRobinHostPolicy.Pick](https://github.com/gocql/gocql/blob/fad1a72d20b87091e46094de8baef56985562690/policies.go#L105) doesn't take into account the possibility of only 1 node remaining. So, at the end of the increment loop, around line 113, `host` will still be `nil`, but this is still passed as a valid host info in 114.

I was doing some chaos testing when all but 1 of the cluster nodes went down, and got the panic.  Maybe the correct fix is to remove the downed node from r.hosts so that [line 100](https://github.com/gocql/gocql/blob/fad1a72d20b87091e46094de8baef56985562690/policies.go#L100) aborts the loop.

**Comment by Zariel** [comment]
The issue that caused this has now been fixed, if there is another issue @rcadena could you open another issue please?
