### ISSUE TITLE
Hardcoded class name check for authentication

### ISSUE THREAD

**Issue by Aorioli** [gocql/gocql#529]
What is the purpose of the following line: https://github.com/gocql/gocql/blob/master/conn.go#L44
Connection to instaclustr nodes fail because they use com.instaclustr.cassandra.auth.SharedSecretAuthenticator, yet simply removing that line works perfectly.

**Comment by Zariel** [comment]
Im not entirely sure, I guess its to guard against using the incorrect authenticator which would probably give some quite obscure error messages. Feel free to add the check to check the instaclutr class as well.

**Comment by Aorioli** [comment]
Whitelisting by class name is not a viable solution, since than the library would need to be updated every time someone uses a non-listed authentication class. Since we can't really check the internals, but need to trust the interface, I suggest the check be completely removed, and if an obscure error pops up, let it.

**Comment by Zariel** [comment]
The issue is that the authenticator wire level is not specified by the protocol but the implementation (as far as I am aware), https://github.com/apache/cassandra/blob/29ec013c2c42dc603c07ca1295b4e1844df01dd5/src/java/org/apache/cassandra/auth/PasswordAuthenticator.java#L198

**Comment by Aorioli** [comment]
Oh, I understand now. 
Since the instaclustr authentication is proprietary we can't write for that, but it seems they only do special things internally: https://www.instaclustr.com/cassandra-authentication-and-encryption-made-easy/

I'll create a pull request.

**Comment by donovanbai-dd** [comment]
Opening this issue again as I'm running into the same thing but with a new authenticator
`unexpected authenticator "com.instaclustr.cassandra.auth.InstaclustrPasswordAuthenticator"`.

Can the hardcoded list please be removed? From what I can tell it seems like unnecessary maintenance. For what it's worth, the Python driver for Cassandra has no such check and handles the new authenticator fine in my testing https://github.com/datastax/python-driver/blob/15d715f4e686032b02ce785eca1d176d2b25e32b/cassandra/auth.py#L260-L263

**Comment by martin-sucha** [comment]
The `PasswordAuthenticator` allows you to add the class name to `AllowedAuthenticators` field.

Unfortunately Cassandra [uses class name](https://github.com/apache/cassandra/blob/1e27ffc6aded5b54b0207b114b154cffbc64dda5/doc/native_protocol_v4.spec#L533-L534) instead of a [SASL mechanism name](https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml) in the protocol (see also https://issues.apache.org/jira/browse/CASSANDRA-11471, which seems to be the correct fix). So now we have one scheme how username+password is encoded, used by many classes and you can't detect if the client uses the same scheme as the server without an allow list of classes.

What happens if you try to use the password authenticator on the client in case the server uses a different mechanism than password for authentication?

**Comment by donovanbai-dd** [comment]
> What happens if you try to use the password authenticator on the client in case the server uses a different mechanism than password for authentication?

I'm not familiar with the details of auth protocols, though this brings up some questions. What different mechanism are you referring to? Can you provide a real-world example of a class that should NOT be allowlisted? Most importantly, why is allowlist not needed in the **Python driver used by cqlsh that is bundled with Cassandra**?

I will provide a real counterexample. Recently we upgraded Cassandra versions and our vendor happened to change the class name of the authenticator. Connecting to the upgrade cluster with cqlsh works perfectly fine. Meanwhile this allowlist caused our go applications to artificially fail (luckily we caught this before production). Now we are blocked and have to do make a whole chain of changes (add class to gocql allowlist, update go applications to use new gocql version, update deployments etc.)
