### ISSUE TITLE
2 seconds for a call to CreateSession

### ISSUE THREAD

**Issue by mattmassicotte** [gocql/gocql#696]
I've been using (and loving) gocql for a while now. Normally, I use Cassandra 2.x, but I've been trying out 3.3 recently. After changing the ProtoVersion to 4, things are working. However, every query now takes almost exactly 2 seconds. The same queries from cqlsh don't have the same problem. Any ideas?

**Comment by MalteJ** [comment]
how do you change the protoversion to 4?

**Comment by mattmassicotte** [comment]
I followed the procedure from this issue:

https://github.com/gocql/gocql/issues/538

Without this, gocql is unable to connect at all.

**Comment by mattmassicotte** [comment]
Welp, I'm mistaken. Obviously something else has changed on my end, because this is now reproducing with 2.x as well. Apologies.

**Comment by mattmassicotte** [comment]
Actually, I narrowed this down a little. Me changing Cassandra versions was a red herring. I also updated gocql, and that was what actually did it. The perf change is in the call to ClusterConfig.CreateSession. It appears that as of recent versions, this call now blocks for almost two seconds.

Is that now expected?

**Comment by MalteJ** [comment]
Same here. I have checked out a commit at Dec 31st 2015 and it's very fast.
But the current version is very slow.
@Zariel do you know what's wrong here?

**Comment by Zariel** [comment]
is it related to #669?

**Comment by MalteJ** [comment]
I am not sure but I don't think so.

**Comment by mattmassicotte** [comment]
More clues. I run cassandra inside a docker container on my mac. There is a single node listed as a seed. This seed IP is visible to the cassandra process, but not from my mac. This makes it look to gocql like the one seed node is down.

**Comment by MalteJ** [comment]
I was using Docker on Mac with the _/cassandra image, too!
So I have created my own cassandra docker image and now I do not have the problems anymore.
You can try my image: `docker run -it -p 9042:9042 parce/cassandra:3.4`
You can find my Dockerfile at https://github.com/parce-iot/docker-cassandra

**Comment by Zariel** [comment]
This related to #703?

**Comment by MalteJ** [comment]
With the official docker cassandra image and current gocql release I still have problems with the delay.
Maybe there are some strange settings in the docker image.

**Comment by MalteJ** [comment]
Anyhow I will not further investigate as I have solved this issue by creating an own image.

**Comment by Highstead** [comment]
Underlying cause is from the initial host lookup.   The quick and dirty solution is:
`gocql.ClusterConfig.DisableInitialHostLookup = true`

I'm probably going to submit a PR in the next few days because there are a few things related to this break which cause some performance problems.  Basically when it does the host lookup docker is returning a 172..... ip range which the gocql client in the application layer cannot see.  As a result you get 3 network timeouts.

Incase i don't...
- On network unreachable probably don't retry 2 more times.
- The initial synchronous connection to the connection pool should probably be established with the ip specified initially as it is gaurnteed to work THEN resolve the other 99 connections.
- When the first connection fails, we're currently not saturating the rest of the pool which is causing performance problem so there me be some gains there as well.

**Comment by dahankzter** [comment]
Any idea what to do about this? The scylladb docker image is also affected. My Linux based setups with the same docker image are not affected however.

**Comment by MalteJ** [comment]
Simply build your own Docker image :wink:

**Comment by dahankzter** [comment]
Yes but upstream would very much like to fix it. Do you know what is different in your build vs Cassandra docker image?

**Comment by penberg** [comment]
@MalteJ So *how* did you fix it in your own image? I'm more than happy to do the same thing for our Scylla image.

**Comment by MalteJ** [comment]
This was my Dockerfile:

    FROM debian:stretch
    RUN apt-get update && apt-get install -y openjdk-8-jre wget && apt-get clean
    RUN cd /opt && wget http://apache.lauf-forum.at/cassandra/3.4/apache-cassandra-3.4-bin.tar.gz && tar xzf apache-cassandra-3.4-bin.tar.gz
    ADD conf/cassandra.yaml /opt/apache-cassandra-3.4/conf/cassandra.yaml
    RUN adduser --system --home /opt/apache-cassandra-3.4 cassandra && chown -R cassandra /opt/apache-cassandra-3.4
    
    EXPOSE 9042
    USER cassandra
    WORKDIR /opt/apache-cassandra-3.4
    CMD /opt/apache-cassandra-3.4/bin/cassandra -f

**Comment by MalteJ** [comment]
I have posted the link to my Cassandra Docker repo before:
https://github.com/parce-iot/docker-cassandra

It is just a very simple Cassandra installation with default parameters.

**Comment by penberg** [comment]
The ``Dockerfile`` looks pretty standard and the AFAICT the only change is in ``cassandra.yaml``:

```patch
--- apache-cassandra-3.4/conf/cassandra.yaml    2016-02-29 22:24:27.000000000 +0200
+++ cassandra.yaml      2016-08-04 12:53:28.746327370 +0300
@@ -563,8 +563,8 @@
 # you can specify which should be chosen using rpc_interface_prefer_ipv6. If false the first ipv4
 # address will be used. If true the first ipv6 address will be used. Defaults to false preferring
 # ipv4. If there is only one address it will be selected regardless of ipv4/ipv6.
-rpc_address: localhost
-# rpc_interface: eth1
+# rpc_address: localhost
+rpc_interface: eth0
 # rpc_interface_prefer_ipv6: false
 
 # port for Thrift to listen for clients on
```

Is that what makes the delay go away?

**Comment by MalteJ** [comment]
I don't know. I have not investigated further.

**Comment by Highstead** [comment]
If you're still seeing the lag after enabling: 
gocql.ClusterConfig.DisableInitialHostLookup = true

It is likely not related to the connection timeout issue.  If the issue persists, it is that the dockerized ip addresses differ from the IP address you're supplying to the gocql driver.  When the driver connects to the node it does a host lookup and then finds a `172.*.*.*` ip address that your local box then tries to access.  

This works on linux (likely) because docker runs natively on linux and on mac / windows it does not.

So an alternative would be to have a separate 'dev build' for your local development... the patch i published earlier should mitigate the problem substantially but won't fix it entirely.

**Comment by dahankzter** [comment]
Yes that is what we do but it forces us to have a config for this because we want to enable it on our servers. 

Should this work on native Mac? I use the new native Mac version but it is still the same.

**Comment by let4be** [comment]
Takes around 30 here... Any idea what to do?

**Comment by dahankzter** [comment]
I simply added a config property that we use that toggles the host lookup.
Not ideal but works.

**Comment by andrehp** [comment]
I had the same problem here using Mac OS, what worker for me was to set the environment variable `CASSANDRA_BROADCAST_ADDRESS` to my computer's IP. Setting `DisableInitialHostLookup` to `true` didn't work completely for me.

**Comment by syhlion** [comment]
I had the same problem too  @andrehp

**Comment by hobbs** [comment]
@let4be same here, DisableInitialHostLookup only reduces connection time to 5 seconds for me.

**Comment by Zariel** [comment]
Can you do a CPU profile and check where the time is being lost?

**Comment by hobbs** [comment]
Interesting. I'm trying to connect to `192.168.99.100:32369` (the container's host), but the error messages are all about the internal IP of the container, `172.17.0.6`
```
2018/04/11 15:52:21 gocql: Session.handleNodeUp: 172.17.0.6:32369
2018/04/11 15:52:21 connection failed "172.17.0.6": dial tcp 172.17.0.6:32369: i/o timeout, reconnecting with *gocql.ConstantReconnectionPolicy
2018/04/11 15:52:23 connection failed "172.17.0.6": dial tcp 172.17.0.6:32369: i/o timeout, reconnecting with *gocql.ConstantReconnectionPolicy
2018/04/11 15:52:25 connection failed "172.17.0.6": dial tcp 172.17.0.6:32369: i/o timeout, reconnecting with *gocql.ConstantReconnectionPolicy
2018/04/11 15:52:26 unable to dial "172.17.0.6": dial tcp 172.17.0.6:32369: i/o timeout
2018/04/11 15:52:26 gocql: Session.handleNodeDown: 172.17.0.6:32369
```

after all this, it still works fine. Can insert/read from the DB no problem.

I couldn't do a full pprof, as they're sampled, it just thinks the whole thing is time.Sleep(). However, dumping the goroutines shows it's spending all it's time at:
`github.com/gocql/gocql/connectionpool.go:519`

**Comment by alijared24m** [comment]
I have the same problem connecting to a cluster on GCP. ~20 seconds without  `DisableInitialHostLookup = true` and ~5 seconds with. Reading and writing to the DB works perfectly fine, it's just creating the initial session that takes forever

**Comment by speier** [comment]
I had similar issues with Docker for Mac, creating session took ~10 seconds by default (and ~5 seconds with initial host lookup disabled).

The solution seems to simply set `CASSANDRA_BROADCAST_ADDRESS` environment variable to `127.0.0.1` (this way doesn't even needed to disable initial host lookup).

Here is a working docker-compose snippet:
```
  cassandra:
    image: cassandra
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
    ports:
      - "9042:9042"
```

**Comment by francisdb** [comment]
having similar problems with scylla, `.DisableInitialHostLookup = true` helped but still takes ~5 sec to connect.

**Comment by cardonator** [comment]
I had the same problem as noted here. I was connecting to a production node through an SSH tunnel. I assume that it's because the nodes return a list of other nodes and gocql tries to connect to them, and one of those nodes it returns is the local node with an unrecognizable IP. Seems like that's the behavior, anyway.

**Comment by nkev** [comment]
I have just one single scyllaDB host in Docker on my MacBook (I've also tried a single Cassandra host with the same result). I can connect to it immediately from DBeaver Enterprise but from GoCQL `createSession()` takes at least 5 seconds, regardless of the parameter variations:

```GO
        cluster := gocql.NewCluster("localhost")
	cluster.Keyspace = "my_app"
	cluster.IgnorePeerAddr = true
	cluster.ConnectTimeout = time.Second * 1
	cluster.DisableInitialHostLookup = true
	cluster.Consistency = gocql.One
	cluster.Port = 32794 // CQL port on Docker
```
Setting `SCYLLA_BROADCAST_ADDRESS=127.0.0.1` env variable makes no difference.

If I turn off WIFI, it connects instantly, but this is not convenient since I need the Internet all the time.

This `createSession()` connection lag is in many threads now and seems to have not been resolved for a long time. Has anyone made any progress? It's frustrating to wait 5 seconds every time you make code changes and rerun your Go app.

**Comment by nkev** [comment]
I finally got it working. The issue was GoCQL on My Mac which is naturally on 127.0.0.1, was trying to connect to 172.17.0.2 (which is the network inside the docker container). I figured this out by running GoCQL with the gocql_debug tag:

```bash
go build -o my_app -tags "gocql_debug" && ./my_app

```
...which showed me this error 3 times:

```
connection failed "172.17.0.2": dial tcp 172.17.0.2:32818: i/o timeout, reconnecting with *gocql.ConstantReconnectionPolicy
```
So I then tried routing the scyllaDB port inside docker (9042) to my network and also changing the scyllaDB broadcast address to match my local network:

```bash
docker run --name scylla1 -p 9042:9042 -d scylladb/scylla --broadcast-address 127.0.0.1 --listen-address 0.0.0.0 --broadcast-rpc-address 127.0.0.1
```

...and GoCQL connection is now instant!
