### ISSUE TITLE
Remove MAC address from TimeUUID

### ISSUE THREAD

**Issue by bronger** [gocql/gocql#700]
Apparently, current Cassandra versions do not include MAC addresses in their `now()` results anymore.  This means a deliberate deviation from UUIDv1, maybe due to security considerations.  May it be sensible/possible to change `gocql.TimeUUID` accordingly?

**Comment by Zariel** [comment]
What are they using instead of the MAC?

**Comment by bronger** [comment]
Yesterday, I failed to find it.  Today, I read the source.  See file src/java/org/apache/cassandra/utils/UUIDGen.java, line 292ff in the Cassandra source code.  Apparently, Cassandra's `now()` has never included the MAC address because this is not possible from within a Java program.  But they would if they could.  Thus, I think that this issue is obsolete then.  The security concerns that a few people (e.g. on Stackoverflow) have raised have not been the motivation for Cassandra's behaviour.

**Comment by bronger** [comment]
The only reason for adding another TimeUUID function would be to mimick Cassandra's behaviour.  I don't know whether this might be helpful, e.g. in mixed scenarios of gocql.TimeUUID and CQL's `now()`.

**Comment by thishitshome** [comment]
This is also problematic by default because Docker uses the same mac address for the first container on every box and just increments it: 02:42:ac:11:00:02

**Comment by martin-sucha** [comment]
I don't think we need to change anything here. The `gocql.TimeUUID` function is documented as returning UUIDv1, so using the MAC address is according to what is documented. If you need to use some other type of UUID because the MAC address is not unique, you can use `TimeUUIDWith` or `RandomUUID` instead.

I'm closing this issue. If there is some other reason why we should remove the mac address, please let me know and we can reopen the issue.
