### ISSUE TITLE
Request: Per-query timeout

### ISSUE THREAD

**Issue by macalinao** [gocql/gocql#793]
Hi, I have some larger queries that I would like to have higher timeouts. Is there any way I can specify a timeout per query?

**Comment by Zariel** [comment]
If wanted to have this as well, I think the confusion comes because we have always used the Timeout option in the config as both dial, read/write and query timeout. This would require clarification in the docs about what the global timeout config applies to, and an optional timeout can be set on Query/Batch.

This should only require a very small functional change which instead of using the config timeout for query response use the supplied one in `exec`, to maintain behaviour we should use the config timeout if the query does not specify one (or just set the query timeout to default to the global timeout).

**Comment by i** [comment]
It'd be great to specify this using context timeouts/deadlines.

**Comment by Zariel** [comment]
This is now doable via contexts
