### ISSUE TITLE
support token aware routing when query is not prepared

### ISSUE THREAD

**Issue by evildecay** [gocql/gocql#844]
Use tokenaware, Routing key is the partition key or token?

```go
// select id, token(id) as token from test
id = "1"
token = "8095949768359927342"

session.Query(cql).RoutingKey([]byte(?)) // ? is id or token
```
Did not see the relevant instructions, can explain? 
If the partition key, there are two fields how to do?

Is that right?
```go
routingKey := append([]byte(id), []byte(id2)...)
```
thanks!

**Comment by robusto** [comment]
You do not need to specify a routing key when using `tokenAwareHostPolicy`.

From gocql/polices.go
```
func (t *tokenAwareHostPolicy) Pick(qry ExecutableQuery) NextHost {
	if qry == nil {
		return t.fallback.Pick(qry)
	}
	routingKey, err := qry.GetRoutingKey()
        ....
	host := t.tokenRing.GetHostForPartitionKey(routingKey)
```

In the Query's "GetRoutingKey" method (https://github.com/gocql/gocql/blob/master/session.go#L768), gocql will attempt to set the routing key based on the partition key columns of the statement's table which is then used to select a host based on the partition key in  "GetHostForPartitionKey".

In the "GetHostForPartitionKey" method, the 'routingkey' is hashed according to the cluster's partitioner which results in the token value that allows us to select a node that would own the replica for this query.

**Comment by evildecay** [comment]
Hi @robusto

I tested the program, if do not specify RoutingKey, gocql can not automatically set RoutingKey.
The TokenAware policy does not work because there is no RoutingKey.
```go
if info.request.colCount == 0 {
    // no arguments, no routing key, and no error
    return nil, nil
}
....
```
I see the source code found here to always return nil
https://github.com/gocql/gocql/blob/master/session.go#L484

Test code written in a problem?
```go
cluster := gocql.NewCluster("192.168.31.201","192.168.31.211","192.168.31.221","192.168.31.231","192.168.31.232")
    cluster.Keyspace = "test"
    cluster.Consistency = gocql.LocalQuorum
    cluster.ProtoVersion = 4 // default 2
    cluster.PoolConfig.HostSelectionPolicy = gocql.TokenAwareHostPolicy(gocql.RoundRobinHostPolicy())
    session, _ := cluster.CreateSession()
    defer session.Close()
    query := session.Query("select id, name, host from test.vobject where id = 320473819929901499")
    iter := cluster.PoolConfig.HostSelectionPolicy.Pick(query)
    for hostResponse := iter(); hostResponse != nil; hostResponse = iter() {
        fmt.Println(hostResponse.Info().Peer().String())
    }
```

Thanks for the reply!

**Comment by robusto** [comment]
Version: Apache Cassandra 3.7 (CCM)
GoCQL: rev 4d2d1ac

Finally got some time to look into this. It does indeed fall back on the RoundRobin selection strategy.

```
gocql.(*tokenAwareHostPolicy).Pick
-->gocql.(*Query).GetRoutingKey()
---->gocql.(*session).routingKeyInfo()
```

The `info.request.colCount` is always 0 for this query after it attempts to be prepared. This is likely because the session is attempting to prepare a query with no actual columns to prepare because the value is hard-coded (i.e. id = 320473819929901499). This seems like a side effect of gocql always preparing queries and how the native protocol responds to this kind of operation.

If you change it to an actual statement that can be prepared:

`query := session.Query("select id, name, host from vobject where id = ?", 320473819929901499)`

You'll see the "Pick()" method successfully selects a Host based on the results of `GetRoutingKey` without falling back on RoundRobin.  

However, note that looping with iter() in your snippet here will cause you to hit the fallback since the executor expect to return successfully in the first pass: https://github.com/gocql/gocql/blob/master/query_executor.go#L25

**Comment by evildecay** [comment]
Hi @robusto 
In accordance with the test that you really do, thank you very much for your answer. 
Hope that the document can be more detailed gocql some, there can be released version of the update to explain the better. Of course, I know this will increase the workload, I hope this project can get better and better.

**Comment by Zariel** [comment]
TBH In this case we should still be able to token aware routing based on the constant passed in, going to reopn

**Comment by nupurbansal8** [comment]
Hi,
Has this support been integrated ?

**Comment by martin-sucha** [comment]
It seems that to support token aware routing for queries that are not prepared, we'd need to parse the query text in gocql.
Parsing CQL text would slow things down and depends on CQL dialect supported by the server.

It seems that queries that are not prepared would not be performance-critical, so it does not matter that they are not routed to the correct node.

If someone needs to route queries based on the CQL text of the statement, they could implement the parsing in an external package and provide the routing key manually.

It does not seem to be worth the effort to implement this, since you can simply replace the constant with a query parameter.
I have updated the documentation to mention this.
