### ISSUE TITLE
Selecting columns from cassandra table having null value

### ISSUE THREAD

**Issue by nupurbansal8** [gocql/gocql#939]
When i am selecting a column having a null value in the cassandra table, on reading through MapScan it is being read as the default value for that column type.

Example, 
If we are selecting a column of bigint type, and it has null value in a row then this is read as 0 in go.

Is this the default behaviour? 
And if yes, is there any way around it so that I can distinguish between actual 0 value and a null value?

**Comment by junchaowu** [comment]
+1 Need for this feature.

**Comment by Zariel** [comment]
Cassandra does not say that a type is 'nullable', in cassandra all types are nullable. MapScan blindly unmarshalls into the default value that corresponds to that type, this is equivalent to writing the following

```go
var p int
iter.Unmarshall(&p)
```

In this case p can never be nil, writing `*p = nil` is not valid. Instead the following needs to be done

```go
p := new(int)
iter.Unmarshall(&p)
```

Here setting `*p = nil` is valid and will set p to be nil. While not obvious the same can be applied using MapScan as show n in #944. For this use case I would recommend using Scan as it clearer as to what is going on.

@junchaowu instead of adding +1 comments please use the thumbs up response in github in the future please.
