### ISSUE TITLE
Is it possible to have a connection string similar to what you'd give a JDBC ?

### ISSUE THREAD

**Issue by ghost** [gocql/gocql#947]

**Comment by hydroflame** [comment]
I have a feeling that strings like `jdbc:cassandra://host1--host2--host3:9160/keyspace1?primarydc=DC1&backupdc=DC2&consistency=QUORUM` are a java specific thing but I need to ask for work related reasons.

**Comment by Zariel** [comment]
Currently not yet, you probably could json serialise the cluster config, or implement yourself something with converts a URI into a Cluster object

**Comment by FarhanSajid1** [comment]
is it worth having this build into the library? It seems like it'd be a benefit because it would make it quicker to create a Cluster object, and it'd resemble what other database libraries do:

This is what a migrator library that I'm currently using does with net like @Zariel mentioned: 
https://github.com/golang-migrate/migrate/blob/master/database/cassandra/cassandra.go#L86-L178

**Comment by martin-sucha** [comment]
In production, you will have many options configured like you need (logger, protocol version, observers, retry policy, host selection policy, ...). There could be many formats of the connection string (JDBC, or the one used in golang-migrate). I think it does not belong to gocql, there should be just one way to setup the cluster. It is trivial to implement parsing of connection string to a ClusterConfig if a user application needs it. It could be shared in some external module.
