### ISSUE TITLE
Tag semver releases

### ISSUE THREAD

**Issue by abhinav** [gocql/gocql#977]
Hello. It looks like gocql doesn't have any tagged releases. Would you please add [semver]-compatible release tags? This will greatly help users of `dep`, `glide`, etc. sanely manage their reliance on gocql APIs.

Thanks!

[semver]: http://semver.org/

**Comment by muirrn** [comment]
Tagged stable releases would be great. Right now there is now way (?) to avoid upgrading today and getting a horrible bug that will be reverted tomorrow for breaking things.

**Comment by dankinder** [comment]
Hi guys, especially as go modules become standard/ubiquitous, it does seem like it's time to add some semver tags. I know it's slightly more overhead (and thanks for the work you guys have put into gocql already!), but I think it would also help with things like adoption and make people feel like gocql really is high quality software (which it is) and not a random off the shelf project that may not work. Not to mention some benefit to the rest of us who _have_ had to roll back to an older version due to a bug that needed fixing.

**Comment by kamyuentse** [comment]
Hi, guys, any update on this?

**Comment by Nikscorp** [comment]
Any update?

**Comment by martin-sucha** [comment]
Having semver tagged versions would also allow adding a user-facing change log (which can be less noisy than git log). Before starting tagging new versions, there are definitely a few things to consider:

- Currently, the major version is v0, do we want to bump it to v1?
  - v1 module users [expect stricter compatibility guarantees](https://blog.golang.org/v2-go-modules) than v0 users.
  - Do we want to make some changes before bumping version to v1?
    - Some gocql forks use tagged versions and are on v1 already. These may not be able to make the same changes in compatible way.
- How often do we want to tag the releases if we decide to do it?

I see a mention of a previous discussion in #975, but I didn't see the discussion itself. What were the pros/cons at that time?

@Zariel any thoughts?

**Comment by sagikazarmark** [comment]
I'd like to second the above: having tagged releases are obviously the right choice today for Go libraries (the tooling is already available for a couple years now).

**Comment by martin-sucha** [comment]
Consensus here seems to be to tag the releases, so I've just pushed  `v1.0.0` tag. :crossed_fingers:
